# Change these first
owner: fr-cleonet # Your GitHub organization or username, where this repository lives
repo: novi-uptime # The name of this repository

sites:
  - name: PROD Novi 
    url: https://groupe-novi-intra.cleonet.fr
  - name: PROD Esthetic Center
    url: https://estheticcenter-intra.cleonet.fr
  - name: PROD Beauty Success
    url: https://beautysuccess-intra.cleonet.fr
  - name: PROD JFG
    url: https://jfgclinic-intra.cleonet.fr
  - name: DEMO Novi 
    url: https://demo.novi-intra.cleonet.fr
  - name: DEMO Esthetic Center
    url: http://demo.estheticcenter-intra.cleonet.fr
  - name: DEMO Beauty Success 
    url: https://demo.beautysuccess-intra.cleonet.fr
  - name: DEMO JFG 
    url: https://demo.jfgclinic-intra.cleonet.fr/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /novi-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Novi Status page
  introTitle: Status page projet Cleonet **Novi**
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/fr-cleonet/novi-uptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
